services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports: ["6333:6333","6334:6334"]
    restart: unless-stopped

  embedchat:
    image: embed:latest
    build: ./embed/app
    container_name: embedBerlin
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=City-Talks
    depends_on: [qdrant]
    stdin_open: true
    tty: true
    command: ["bash","-lc","python Berlin-Agent.py"]

  alertsapi:
    image: berlin-rest-api:latest
    build: ./berlin-rest-api/app
    container_name: restapiBerlin
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=City-Talks
    depends_on: [qdrant]
    ports: ["8080:8080"]
volumes:
  qdrant_storage: