apiVersion: v1
kind: ConfigMap
metadata: { name: configmap-berlin }
data:
  QDRANT_URL: "http://qdrant:6333"
  QDRANT_COLLECTION: "City-Talks"
  EMBED_MODEL: "text-embedding-3-small"
  MIN_SCORE: "0.5"
  TOP_K: "5"