---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-openai
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgDHN3EyvfDUAfw/nrHECtw0n9YWBhut+3npWaEUF/tPVA5TzD4phYDhqhSTjsiSDgyO+csXWQwB6P2blHKoPQDivgJwFKWsFjytktnlvSmx92WJqykZF4kdXMxoDEal0S3Yi7538+k5g3Afcu0CjLP7jPvO2uGsKeRP/OcoCQpSuwDqlF7speSuL34BE+WAjsqs8c4vBLOuLBfLySwvsxxreCxMBq8NpoNNAga1yhPsf9uombsvZHWVUv1LWuNCnOp4JuQWyPlyWASbOXLfnuAXeVWmgat5osfeHfSbdGKvHaIfISpOqRS5pAHCP2u8tM9lDcH4XQHQ3hwRdSXjTQlpkrh2ybamUCOPUYWwur0jUBEZMsoXKZuDG2fOlpQZdNOAdjdujD8Nh4gQnPfIJ3ghPTYrbaMF66f/GlKRMztOnl5KkHOlKMq9mwKz/9kqk9kqeEON0FbCr93OaH31DDnDnSJicg7dewtZHkbfBdURRD5di7b3993L6JFNKMS2aoFzy4UhxSYFRk8UlScX0Hh2eWP3dSmO2fCMq3T24o09VfNSFE/BnzMhiUJb0nQQwW55hk/KPIRqppO5jHUxcLQZM73Ruk8KsoJwlSsoy99kuFaG+kIAU63P0UDdhho6+PX/yqIFIZ4QNOqcvxASw/3W20vNBkd3X2m0rbJi1/LXf+emOlnrrP8ODyczNPsOeQ0T8eL39EESRedk7c6xCi7BYp2CGc8kYYh1D/dD4oHDN3SsPhpO6BLSR0LM94ON2ralmyttguX8PNmG4MpUx+gmqpsrf0dynIwlRb8OumK4natmxiVvEbvp1TA1WE7vrieSXKM1mClLK/aoH+vZzAXTf9kdcdzuitr/XEKUly+9ZKk8uXpFTvdEPhWo/iiDevTDrWkfQlaQKlTg+WuGljMrsy3v4Q==
  template:
    metadata:
      name: secret-openai
      namespace: default
    type: Opaque
